%YAML 1.2
---
# DBT Sample Settings file implemented in YAML format (see the XML format for the original reference version)
# in YAML we can't use attributes, so this means more properties are added.
# type: may not be required since YAML does typecast value: but we may need to distinguish other types, like combo
# detect and disabled are messier as a bool insetad of an attribute, but they still work.

graphics:
  - key:          Windowed
    value:        No
    type:         bool
    arg:          w
    displaytext:  Windowed mode
    
  - key:          Resolution
    value:        1680x1050
    type:         combo
    arg:          res
    option:       1680x1050
    option:       800x600
    displaytext:  Screen Resolution
    detect:       Yes
    
sound:
  - key:          Sound
    value:        No
    type:         bool
    displaytext:  Enable Sound
    disabled:     Yes
    
gameplay:
  - key:          TimedDays
    value:        No
    type:         bool
    displaytext:  Use Timed Days
    tooltip:      Days end on a timer instead of after a fixed number of Actions
    
  - key:          ActionsPerDay
    value:        4
    type:         int
    displaytext:  Actions per Day
    tooltip:      The number of Actions before a Day ends, if Timed Days aren't used
    dev:          Yes
    
dev: